apiVersion: v2
appVersion: v0.0.0
description: Opinionated Laravel Helm Charts
name: laravel
version: 0.0.2
kubeVersion: ">=1.19.0-0"
keywords:
- laravel
home: https://github.com/nicko170/charts/tree/main/charts/stable/laravel
icon: https://laravel.app/icon
sources:
- https://github.com/nicko170/laravel
maintainers:
- name: Nick Pratley
  email: nick@npratley.net
dependencies:
- name: postgresql
  version: 11.1.3
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 16.4.5
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
