#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: docker.io/nick170/rfspager
  tag: v1.1.4
  pullPolicy: IfNotPresent

schedule: "*/1 * * * *"
scheduleCommand: /cnb/process/schedule

workerCommand: /cnb/process/worker
workerCount: 5

strategy: RollingUpdate

env:
  TZ: Australia/Sydney
  PORT: 8080
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

redis:
  master:
    persistence:
      enabled: true
      size: 1Gi
  enabled: true
  architecture: standalone
  auth:
    enabled: false

postgresql:
  enabled: false
  postgresqlUsername: rfspager
  postgresqlPassword: rfspager
  postgresqlDatabase: rfspager
  persistence:
    enabled: true
    size: 5Gi
