{{- if .Values.ingress.enabled}}
{{- $fullName := include "laravel.names.fullname" . -}}
{{- $ingressName := $fullName -}}
{{- $values := .Values.ingress -}}
{{- $port := .Values.service.port -}}
{{- $defaultServiceName := $fullName -}}
{{- $isStable := include "laravel.capabilities.ingress.isStable" . }}

{{- if hasKey . "ObjectValues" -}}
{{- with .ObjectValues.ingress -}}
{{- $values = . -}}
{{- end -}}
{{ end -}}

apiVersion: {{include "laravel.capabilities.ingress.isStable" . }}
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
  {{ include "laravel.labels" . | nindent 4 }}
  {{ include "laravel.labels.web" . | nindent 4 }}
  {{- with $values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  {{- if and $values.ingressClassName }}
  ingressClassName: {{ $values.ingressClassName }}
  {{- end }}
  {{- if $values.tls }}
  tls:
    {{- range $values.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ tpl . $ | quote }}
          {{- end }}
      {{- if .secretName }}
      secretName: {{ tpl .secretName $ | quote}}
    {{- end }}
  {{- end }}
  {{- end }}

    {{- range $values.hosts }}
  rules:
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- $service := $defaultServiceName -}}
          {{- if .service -}}
          {{- $service = default $service .service.name -}}
          {{- $port = default $port .service.port -}}
          {{- end }}
          - path: {{ tpl .path $ | quote }}
            {{- if $isStable }}
            pathType: {{ default "Prefix" .pathType }}
            {{- end }}
            backend:
              {{- if $isStable }}
              service:
                name: {{ $service }}-web
                port:
                  number: {{ $port }}
              {{- else }}
              serviceName: {{ $service }}
              servicePort: {{ $port }}
          {{- end }}
  {{- end }}
  {{- end }}



{{- end }}
