{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.names.fullname" . }}-workers
  labels:
  {{ include "laravel.labels" . | nindent 4 }}
  {{ include "laravel.labels.worker" . | nindent 4 }}

spec:
  selector:
    matchLabels:
  {{ include "laravel.labels.worker" . | nindent 6 }}

  replicas: {{ default 1 .Values.worker.count }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
      {{ include "laravel.labels" . | nindent 8 }}
      {{ include "laravel.labels.worker" . | nindent 8 }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      containers:
        - name: {{ include "laravel.names.name" . }}-worker
          image: {{ printf "%s:%s" .Values.image.repository (default .Chart.AppVersion .Values.image.tag) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.worker.command }}
          command:
            - {{ . }}
              {{- end }}
          env:
            - name: "APP_VERSION"
              value: {{ quote .Values.image.tag }}
          {{- with .Values.env }}
            {{- range $k, $v := . }}
            {{- $name := $k }}
            {{- $value := $v }}
            {{- if kindIs "int" $name }}
            {{- $name = required "environment variables as a list of maps require a name field" $value.name }}
            {{- end }}
            - name: {{ quote $name }}
              {{- if kindIs "map" $value -}}
              {{- if hasKey $value "value" }}
              {{- $value = $value.value -}}
              {{- else if hasKey $value "valueFrom" }}
              {{- toYaml $value | nindent 6 }}
              {{- else }}
              {{- dict "valueFrom" $value | toYaml | nindent 6 }}
              {{- end }}
              {{- end }}
              {{- if not (kindIs "map" $value) }}
              {{- if kindIs "string" $value }}
              {{- $value = tpl $value $ }}
              {{- end }}
              value: {{ quote $value }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if or .Values.envFrom }}
          envFrom:
          {{- with .Values.envFrom }}
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 12 }}
  {{- end }}
  {{- end }}
{{- end }}
