{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{- define "oxidized.config" -}}
persistence:
  oxidized-config:
    enabled: "true"
    mountPath: "/etc/oxidized"
    type: "custom"
    volumeSpec:
      configMap:
        name: {{ printf "%v-config" (include "common.names.fullname" .) }}
        defaultMode: 256
        optional: true
{{- end -}}


{{- $_ := mergeOverwrite .Values (include "oxidized.config" . | fromYaml) -}}

{{ include "common.all" . }}