{{- if .Values.scheduleCommand -}}
# ------------------- CronJob ------------------- #
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "common.names.fullname" . }}-cronjob
  labels:
  {{- include "common.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "common.names.fullname" . }}-backup
          labels:
        {{- include "common.labels.selectorLabels" . | nindent 12 }}
        spec:
          {{- with (include "common.controller.volumes" . | trim) }}
          volumes:
          {{- nindent 12 . }}
          {{- end }}
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          containers:
          {{- include "rfspager.cronContainer" . | nindent 12 }}

  {{- end -}}
